config/routes.rb
Rails.application.routes.draw do
  get "settings/payment-info/users/auth/stripe_connect/callback", to:"event#stripe_callback"
  #get 'event/stripe_callback'

  get 'event/payment_profile'

  resources :services
  resources :service_categories
  root to: "home#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { registrations: 'registrations' ,omniauth_callbacks: 'users/omniauth' }

  resources :charges
  resources :posters
  resources :categories
  resources :products do
    resources :reviews
  end
  resources :questions do
    resources :answers
  end
  resources :types
  resources :pets
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :user
    has_many :answers

    validates:title,presence: true 
    validates:content,presence: true 

    #for search and filter
    filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [
     :search_query,
     :sorted_by,
     
     
    ]
    )

    #scopes
    
    scope :search_query, lambda { |query|
    return nil  if query.blank?
    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conditions = 2
    where(
      terms.map {
        or_clauses = [
          "LOWER(questions.content) LIKE ?",
          "LOWER(questions.title) LIKE ?",
          

          
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
}

    scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/
      order("questions.created_at #{ direction }")
    
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
}

def self.options_for_sorted_by
    [
      
      ['Date created (newest first)', 'created_at_desc'],
      ['Date created (oldest first)', 'created_at_asc'],
     
    ]
end

def decorated_created_at
    created_at.to_date.to_s(:long)
end




end

app/controllers/questions_controller.rb
require 'builder'
#require 'will_paginate'
#include ActionView::Helpers::NumberHelper

class QuestionsController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :check_user,only: [ :edit, :update, :destroy]
  private

    def question_params
      params.require(:question).permit(:content, :user_id , :title)
    end
  
  public 
  def index
    @filterrific = initialize_filterrific(
      Question,
      params[:filterrific],
      :select_options => {
        sorted_by: Question.options_for_sorted_by,
        
      }
    ) or return
    @questions = @filterrific.find.page(params[:page])
 
    respond_to do |format|
      format.html
      format.js
    end
  end

  def check_user
    @question=Question.find(params[:id])
    if current_user.id != @question.user_id
      redirect_to(questions_path,notice:"Sorry,you don't have permission to perform this action")
    end
   end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_carousel.html.erb
<div class="col-lg-9">

<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
    <%=image_tag("question/q2.jpg")%>
    
    </div> 
    <div class="carousel-item">
    <%=image_tag("question/Question-Answer.jpg")%>
    </div>
    <div class="carousel-item">
    <%=image_tag("question/question-mark.jpg")%>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/questions/_form.html.erb
<%= bootstrap_form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.text_field :title, id: :question_title %>
    <%= form.text_area :content, id: :question_content %>
    <%= form.hidden_field :user_id,value:current_user.id %>
     
    <div class="text-center">
    <button type="submit" value="Send" id="submit" class="btn btn-primary btn-block">Submit</button>
    <%= link_to 'Back', questions_path %>
</div>

<% end %>

app/views/questions/_list.html.erb
<% questions.each do |question| %>
    <div class="card mt-4">
      
      <div class="card-body">
        <h3 class="card-title"><%=link_to question.title,question %></h3>
        
        <p class="card-text"><%=question.content %></p>
        <span class="text-info">Posted by <%= question.user.try(:name) %> on <%= question.created_at.to_date %> </span>
        
      </div>
    </div>
    <!-- /.card -->
    <% end %>

app/views/questions/_searchSidebar.html.erb
<div class="row">

        <div class="col-lg-3">
          <h1 class="my-4">Q&A</h1>
          <%= form_for_filterrific @filterrific do |f| %>

            <div class="form-group">
                <label>Search</label>
      
                <%= f.text_field(:search_query,
                class:'filterrific-periodically-observed form-control'
              ) %>
            </div>
            

            <div class="form-group" >
            <label>Sorted by</label>
            <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by],class:'form-control') %>
             </div>
    
          <div>
            <%= link_to(
              'Reset filters',
              reset_filterrific_url,
            ) %>
          </div>
          <%# add an automated spinner to your form when the list is refreshed %>
          <%= render_filterrific_spinner %>
        <% end %>
        <hr>
  <br/>
  <div class="text-center">
  
  <%= link_to 'Ask a question', new_question_path,class:'btn btn-success' %>
   
  </div>
        </div>

app/views/questions/edit.html.erb
<%= render 'userNavBar',user: current_user %>
<div class="container">
    <div class="card card-login mx-auto mt-5">
    <div class="card-header">Edit Your Question</div>
    <div class="card-body">

<%= render 'form', question: @question %>
<hr>
     
<div class="text-center">
<small>Want to delete?</small>
<br/>
<%= link_to "Delete Question", @question, data: { confirm: "Are you sure?" }, method: :delete,class:"btn btn-danger" %>
</div>
</div>
</div>
</div>

</div>
<br/>
<br/>
<%= render 'footer' %>

app/views/questions/index.html.erb
<%= render 'userNavBar',user: current_user %>
<%= render 'questions/searchSidebar' %>
<%= render 'carousel' %>
<div class="col-lg-9">
<div id="filterrific_results">

  
  <div id="questions" >
  <%= render 'list',questions: @questions %>
  </div>
<br>
<br>

</div>
</div>
<!-- /.col-lg-9 -->

<%= render 'endIndexPage' %>
<%= render 'footer' %>

app/views/questions/index.js.erb
<% js = escape_javascript(
  render(partial: 'questions/list', locals: { questions: @questions })
) %>
$("#questions").html("<%= js %>");

app/views/questions/new.html.erb
<%= render 'userNavBar',user: current_user %>

<div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Ask a Question?</div>
      <div class="card-body">

<%= render 'form', question: @question %>


</div>
</div>
</div>

app/views/questions/show.html.erb
<%= render 'userNavBar',user: current_user %>

<div class="row">

<div class="col-lg-2">
 
</div>
<!-- /.col-lg-2 -->

<div class="col-lg-9">

  <div class="card mt-4">
    
    <div class="card-body">
      <h3 class="card-title"><%=@question.title %></h3>
      
      <p class="card-text"><%=@question.content %></p>
      <span class="text-info">Posted by <%= @question.user.try(:name)%> on <%= @question.created_at.to_date %> </span>
    </div>
  </div>
  <!-- /.card -->

  <div class="card card-outline-secondary my-4">
   
    <div class="card-body">
    <%= render "answers/form" %> 
    </div>
  </div>
  <!-- /.card -->

  <div class="card card-outline-secondary my-4">
    <div class="card-header">
     Answers
    </div>
    <div class="card-body" id="ans">
    <%= render @question.answers.order(created_at: :desc) %>
   
      
    </div>
  </div>
  <!-- /.card -->
  <br/>

<%= link_to "Back", products_path %>
&nbsp;&nbsp;
<% if current_user.id == @question.user_id %>
<%= link_to 'Edit', edit_question_path(@question) ,class:"btn btn-warning" %> 
<% end %>
<br/>
<br/>

</div>
<!-- /.col-lg-9 -->


</div>