config/routes.rb
Rails.application.routes.draw do
  get "settings/payment-info/users/auth/stripe_connect/callback", to:"event#stripe_callback"
  #get 'event/stripe_callback'

  get 'event/payment_profile'

  resources :services
  resources :service_categories
  root to: "home#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { registrations: 'registrations' ,omniauth_callbacks: 'users/omniauth' }

  resources :charges
  resources :posters
  resources :categories
  resources :products do
    resources :reviews
  end
  resources :questions do
    resources :answers
  end
  resources :types
  resources :pets
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
  <%=link_to(image_tag(user.image.thumb.url, alt: 'Photo',class:"img-circle"),user.image.url,target:'_blank')  if user.image? %>
  
  <a class="navbar-brand" href="users/edit">&nbsp;&nbsp;<%= user.name %></a>

    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
      <li class="nav-item">
      <a class="nav-link" href="/">Home</a>
      </li>
       
        <li class="nav-item">
        <a class="nav-link" href="/pets">Pet Sale</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/services">Services</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/products">Store</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/posters">Lost&Found</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/questions">Q&A</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="/users/sign_out" data-method="DELETE" >Log out</a>
      </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<%= render 'nav',user: current_user %>

<header>
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <!-- Slide One - Set the background image for this slide in the line below -->
          <div class="carousel-item home  active" >
          <%=image_tag("homepage/cat.jpg")%>
            <div class="carousel-caption d-none d-md-block">
            <%= link_to "Pet Sale" ,pets_path,:class => "btn btn-lg btn-outline-warning" %> 
              <h2>Sell,Buy or Adopt a Pet.</h2>
            </div>
          </div>
          <!-- Slide Two - Set the background image for this slide in the line below -->
          <div class="carousel-item home" >
          <%=image_tag("homepage/vet.jpg")%>
            <div class="carousel-caption d-none d-md-block">
            <%= link_to "Services" ,services_path,:class => "btn btn-lg btn-outline-danger" %> 
  
            </div>
          </div>
          <!-- Slide Three - Set the background image for this slide in the line below -->
          <div class="carousel-item home" >
          <%=image_tag("homepage/lost.jpg")%>
            <div class="carousel-caption d-none d-md-block">
        
            <%= link_to "Lost&Found" ,posters_path,:class => "btn btn-lg btn-outline-warning" %> 
            <br/><br/>
            </div>
          </div>
          <!-- Slide Four - Set the background image for this slide in the line below -->
          <div class="carousel-item home" >
          <%=image_tag("homepage/store.jpg")%>
            <div class="carousel-caption d-none d-md-block">
            <%= link_to "Click to Shop" ,products_path,:class => "btn btn-lg btn-outline-dark" %> 
             <br/><br/>
             <br/><br/>
            </div>
          </div>

          <!-- Slide Five - Set the background image for this slide in the line below -->
          <div class="carousel-item home" >
          <%=image_tag("homepage/q.jpg")%>
            <div class="carousel-caption d-none d-md-block">
            <%= link_to "Get Answers" ,questions_path,:class => "btn btn-ld btn-outline-warning" %> 
            
            </div>
          </div>



        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </header>


    <%= render 'footer' %>


 