config/routes.rb
Rails.application.routes.draw do
  get "settings/payment-info/users/auth/stripe_connect/callback", to:"event#stripe_callback"
  #get 'event/stripe_callback'

  get 'event/payment_profile'

  resources :services
  resources :service_categories
  root to: "home#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { registrations: 'registrations' ,omniauth_callbacks: 'users/omniauth' }

  resources :charges
  resources :posters
  resources :categories
  resources :products do
    resources :reviews
  end
  resources :questions do
    resources :answers
  end
  resources :types
  resources :pets
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    belongs_to :type
    has_many :reviews
    belongs_to :user

    validates:name,presence: true 
    validates:price,presence: true 
    validates:user_id,presence: true 
    validates:category_id,presence: true 
    validates:type_id,presence: true 
    validates:brand,presence: true 
    validates:productImage,presence: true 

    mount_uploader :productImage, ImageUploader

    #for search and filter
    filterrific(
   default_filter_params: { sorted_by: 'created_at_desc' },
   available_filters: [
     :sorted_by,
     :search_query,
     :with_type_id,
     :with_category_id
   ]
 )
   #scopes
   scope :search_query, lambda { |query|
    return nil  if query.blank?
    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conditions = 3
    where(
      terms.map {
        or_clauses = [
          "LOWER(products.name) LIKE ?",
          "LOWER(products.description) LIKE ?",
          "LOWER(products.brand) LIKE ?"
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )

}

scope :sorted_by, lambda { |sort_option|
# extract the sort direction from the param value.
direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
case sort_option.to_s
when /^created_at_/
  order("products.created_at #{ direction }")
when /^price_/
  order("LOWER(products.price) #{ direction }")

else
  raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
end
}

scope :with_type_id, lambda { |type_ids|
where(:type_id => [*type_ids])
}

scope :with_category_id, lambda { |category_ids|
where(:category_id => [*category_ids])
}

def self.options_for_sorted_by
    [
      
      ['Date created (newest first)', 'created_at_desc'],
      ['Date created (oldest first)', 'created_at_asc'],
      ['Price(high to low)', 'price_asc'],
      ['Price (low to high)', 'price_desc'],
      
    ]
end 


  
end

app/controllers/products_controller.rb
require 'builder'
#require 'will_paginate'
#include ActionView::Helpers::NumberHelper

class ProductsController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :check_store,only: [:new , :edit, :update, :destroy, :create]
  before_action :check_stripe_connected,only: [:new]
  private

    def product_params
      params.require(:product).permit(:name, :price, :description, :user_id, :type_id, :category_id, :brand, :productImage)
    end

    public 
    def index
      @filterrific = initialize_filterrific(
        Product,
        params[:filterrific],
        :select_options => {
        sorted_by: Product.options_for_sorted_by,
        with_type_id: Type.options_for_select,
        with_category_id: Category.options_for_select,
      }
      ) or return
      @products = @filterrific.find.page(params[:page])
   
      respond_to do |format|
        format.html
        format.js
      end
    end
    def check_store
      if current_user.is_store != 1
        redirect_to(products_path,notice:"Sorry,you don't have permission to perform this action")
    end
  end
    def check_stripe_connected
      if current_user.stripe_uid == nil
        redirect_to(event_payment_profile_path,notice:"Please,create a stripe account first")
      end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_carousel.html.erb
<div class="col-lg-9">

<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
    <%=image_tag("store/catfoodcans.jpg")%>
    
    </div> 
    <div class="carousel-item">
    <%=image_tag("store/cat-toys.jpg")%>
    </div>
    <div class="carousel-item">
    <%=image_tag("store/Pet-toys.jpg")%>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/products/_filterbar.html.erb
<div class="row">

 <div class="col-lg-3">

 <h1 class="my-4"><%= title %></h1>
 <%= form_for_filterrific @filterrific do |f| %>

    <div class="form-group">
      <label>Search</label>
      
      <%= f.text_field(:search_query,
        class:'filterrific-periodically-observed form-control'
      ) %>
    </div>

    <div class="form-group">
      <label>Type</label>
      <%= f.select(
        :with_type_id,
        @filterrific.select_options[:with_type_id],
        { include_blank: '- Any -' },
        class:'form-control'
      ) %>
    </div>
    <div class="form-group">
      <label>Category</label>
      <%= f.select(
        :with_category_id,
        @filterrific.select_options[:with_category_id],
        { include_blank: '- Any -' },
        class:'form-control'
      ) %>
    </div>
    
   <div class="form-group" >
      <label>Sorted by</label>
      <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by],class:'form-control') %>
    </div>
    <div>
      <%= link_to(
        'Reset filters',
        reset_filterrific_url,
      ) %>
    </div>
    <%# add an automated spinner to your form when the list is refreshed %>
    <%= render_filterrific_spinner %>
  <% end %>
  <hr>
  <br/>
  <div class="text-center">
  <% if current_user.is_store == 1 %> 
  <%= link_to 'Add a new product', new_product_path,class:'btn btn-success' %>
  <br/>
  <br/>
  <br/>
  <%= link_to 'See your Balance', event_payment_profile_path,class:'btn btn-warning' %>
   <% end %>
  </div>
 
 </div>

app/views/products/_form.html.erb
<%= bootstrap_form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <%= form.text_field :name, id: :product_name %>
    <%= form.text_field :brand, id: :product_brand %>
    <%= form.number_field :price, id: :product_price %>
    <%= form.file_field :productImage %>
    <%= form.text_area :description, id: :product_description %>
    <%= form.hidden_field :user_id,value:current_user.id %>
    <%= form.select :type_id, options_for_select(Type.all.map {|t|[t.name, t.id]})  %>
    <%= form.select :category_id, options_for_select(Category.all.map {|c|[c.name, c.id]}) ,class:'form-control' %>
  

    <div class="text-center">
    <button type="submit" value="Send" id="submit" class="btn btn-primary btn-block">Submit</button>
    <%= link_to 'Back', pets_path %>
    </div>
      
    <% end %>

app/views/products/_list.html.erb
  

<div class="row">
<% objects.each do |obj| %>
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
              
              <%=link_to(image_tag(obj.productImage.thumbIndex.url, alt: 'Photo'),obj.productImage.url,target:'_blank')  if obj.productImage? %>
                <div class="card-body">
                  <h4 class="card-title">
                    <%= link_to obj.name ,obj %>
                  </h4>
                  <h5><%= obj.price %> EGP</h5>
                  <h5><%= obj.brand %></h5>
                  <p class="card-text"><%= obj.category.name %></p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">created <%= obj.created_at.to_date %></small>
                </div>
              </div>
            </div>
            <% end %>
  </div>
  

app/views/products/edit.html.erb
<%= render 'userNavBar',user: current_user %>
<div class="container">
    <div class="card card-login mx-auto mt-5">
    <div class="card-header">Edit Your Product</div>
    <div class="card-body">
<%= render 'form', product: @product %>
<hr>
     
<div class="text-center">
<small>Want to delete?</small>
<br/>
<%= link_to "Delete Poster", @product, data: { confirm: "Are you sure?" }, method: :delete,class:"btn btn-danger" %>
</div>
</div>
</div>
</div>

</div>
<br/>
<br/>
<%= render 'footer' %>

app/views/products/index.html.erb
<%= render 'userNavBar',user: current_user %>
<%= render 'filterbar',title: "Pet Store " %>
<%= render 'carousel' %>
<div id="products">

<%= render 'list',objects:@products %>


</div>


<%= render 'endIndexPage' %>
<%= render 'footer' %>

app/views/products/index.js.erb
<% js = escape_javascript(
    render(partial: 'products/list', locals: { objects: @products })
  ) %>
  $("#products").html("<%= js %>");

app/views/products/new.html.erb
<%= render 'userNavBar',user: current_user %>

<div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Create a new Product</div>
      <div class="card-body">
     
<%= render 'form', product: @product %>

</div>
</div>
</div>

</div>
<br/>
<br/>
<%= render 'footer' %>

app/views/products/show.html.erb
<%= render 'userNavBar',user: current_user %>


<div class="row">

<div class="col-lg-2">
 
</div>
<!-- /.col-lg-2 -->
<div class="col-9 ">

<div class="card mt-4">
<%=link_to(image_tag(@product.productImage.showImg.url, alt: 'Photo'),@product.productImage.url,target:'_blank')  if @product.productImage? %>



  <div class="card-body">
    <h3 class="card-title"><%=@product.name%></h3>
    
    <h4>Brand:<%=@product.brand%></h4> 
    <h4 class="card-text">Description:<%=@product.description%></h4>
    <h4>Price:<%=@product.price%>EGP</h4>


<%= form_tag charges_path do %>
  <article>
  
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    
  </article>
   <%= hidden_field_tag 'amount', @product.price * 100  %>
   <%= hidden_field_tag 'account_id', @product.user.stripe_uid %>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Get Your Product"
          data-amount= <%=@product.price * 100%> 
          data-locale="auto"></script>
<% end %>


    
    

    
  </div>
</div>
<br/>
<div class="card card-outline-secondary my-4">
   
    <div class="card-body">
    <%= render "reviews/form" %> 
    </div>
  </div>
  <!-- /.card -->

  <div class="card card-outline-secondary my-4">
    <div class="card-header">
     Reviews
    </div>
    <div class="card-body" id="rev">
    <%= render @product.reviews.order(created_at: :desc) %>
   
      
    </div>
  </div>
  <!-- /.card -->

<br/>

<%= link_to "Back", products_path %>
&nbsp;&nbsp;
<% if current_user.is_store == 1 %>
<%= link_to 'Edit', edit_product_path(@product) ,class:"btn btn-warning" %> 
<% end %>
<br/>
<br/>
<!-- /.card -->
</div>


<!-- /.col-lg-9 -->

</div>

</div>
<%= render 'footer' %>