config/routes.rb
Rails.application.routes.draw do
  get "settings/payment-info/users/auth/stripe_connect/callback", to:"event#stripe_callback"
  #get 'event/stripe_callback'

  get 'event/payment_profile'

  resources :services
  resources :service_categories
  root to: "home#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { registrations: 'registrations' ,omniauth_callbacks: 'users/omniauth' }

  resources :charges
  resources :posters
  resources :categories
  resources :products do
    resources :reviews
  end
  resources :questions do
    resources :answers
  end
  resources :types
  resources :pets
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < InheritedResources::Base
 
  private

    def review_params
      params.require(:review).permit(:review, :user_id, :product_id)
    end

  public 
  def create
    @product = Product.find(params[:product_id])
    params.permit!
    @review = @product.reviews.create(params[:review])

    respond_to do |format|
        format.html { redirect_to product_path(@product) }
        format.js 
   end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@product, @product.reviews.build], remote: true) do |f| %>
  <%= f.text_area :review ,class:'form-control' %><br />
  <%= f.hidden_field :user_id,value:current_user.id %>
  <%= f.hidden_field :product_id,value:@product.id %>
  <button type="submit" value="Send" id="submit" class="btn btn-primary ">Send</button>
<% end %>

  

app/views/reviews/_review.html.erb
<p> <%= review.review %></p>
 <small class="text-muted">Posted by <%= review.user.try(:name) %> on <%= review.created_at.try(:to_date) %> </small>
 <hr>

app/views/reviews/create.js.erb
$('#rev').html("<%=j render @product.reviews.order(created_at: :desc) %>");

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Review</th>
      <th>User</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.review %></td>
        <td><%= review.user_id %></td>
        <td><%= review.product_id %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Review:</strong>
  <%= @review.review %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @review.product_id %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>